[package]
name = "blp-rs"
version = "0.1.0"
authors = ["nazarpunk <nazarpunk@gmail.com>"]
repository = "https://github.com/WarRaft/JASS-Tree-sitter-rust"
edition = "2024"

[dependencies]
image = "0.25.6"
num_enum = "0.7.4"
byteorder = "1.5.0"
jpeg-decoder = "0.3.2"
walkdir = "2.5.0"
clap = { version = "4.5.45", features = ["derive"] }
rfd = "0.15.4"
arboard = "3.6.1"
egui = "0.32.1"
eframe = { version = "0.32.1", features = ["wgpu"] }

[[bin]]
name = "blp_rs"
path = "main.rs"

[lib]
name = "blp_rs"
path = "src/lib.rs"
