[package]
name = "blp-rs"
version = "0.1.2"
authors = ["nazarpunk <nazarpunk@gmail.com>"]
repository = "https://github.com/WarRaft/JASS-Tree-sitter-rust"
edition = "2024"

[dependencies]
image = "0.25.8"
num_enum = "0.7.4"
byteorder = "1.5.0"
directories = "6.0.0"
jpeg-decoder = "0.3.2"
walkdir = "2.5.0"

clap = { version = "4.5.47", features = ["derive"] }
rfd = "0.15.4"
arboard = "3.6.1"
egui = "0.32.2"
mozjpeg = "0.10.13"
eframe = { version = "0.32.2", features = ["wgpu"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"

[[bin]]
name = "blp_rs"
path = "main.rs"

[lib]
name = "blp_rs"
path = "src/lib.rs"

[package.metadata.bundle]
name = "blp-rs"
identifier = "com.blp.blp-rs"
#icon = ["assets/icon.icns"]          # опционально
#resources = ["assets"]               # опционально
category = "public.app-category.developer-tools"
short_description = "BLP viewer"
# macOS-специфика:
osx_minimum_system_version = "10.13"
